name: multiomics-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - biopython
  - jupyterlab
  - requests
  - pip
  - pip:
      - gseapy
      - mygene